.tags: &tags
- personal-minikube-tassis

stages:
- lint
- build
- publish

lint:
  stage: lint
  tags: *tags
  image: thulioassis/bazel-docker-image:0.29.1
  script:
  - ./dev/linters/shellcheck.sh

build:chart:
  stage: build
  tags: *tags
  image: thulioassis/bazel-docker-image:0.29.1
  script:
  - bazel build //deploy/helm/scf:chart
  - mkdir -p output; (cd bazel-bin/deploy/helm/scf; tar cf - .) | (cd output; tar xvf -)
  - |-
    set -o errexit -o nounset

    built_file="$(find output/ -name 'scf-*.tgz' -print0 | xargs -0 basename)"
    commit_hash="$(git rev-parse --short HEAD)"
    release_filename="$(basename "${built_file}" .tgz)-${commit_hash}"
    if [ -n "$(git status --porcelain)" ]; then
      release_filename="${release_filename}-dirty"
    fi

    mv "output/${built_file}" "output/${release_filename}.tgz"
  artifacts:
    paths:
    - output/scf-*.tgz
    expire_in: 1 week

publish:chart:
  stage: publish
  tags: *tags
  image: opensuse/leap:15.1
  script:
  - ls output/
